inputs:
    - file:
          host: 10.0.3.31
          group: customer-gateway-tengine
          type: program_log_no_muiltline
          dir: /datasas/logs/customer_gateway
          pattern: customer_gateway_access_.*\.log
          batch_size: 1000